# Generated by Django 5.0.6 on 2026-04-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_task_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentmemory",
            new_name="agent_memor_agent_t_ce224a_idx",
            old_name="agent_memory_type_idx",
        ),
        migrations.AddField(
            model_name="taskprogress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
