# Generated by Django 5.0.6 on 2026-06-05 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_add_memory_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('completed', '已完成'), ('failed', '失败'), ('aborted', '已中止')], max_length=16)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('step_results', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('elapsed_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wf_hist_user_created_idx')],
            },
        ),
    ]
