# Generated by Django 5.0.6 on 2026-06-16 12:55

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_add_scheduled_one_time_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
