# Generated by Django 5.0.6 on 2026-06-16 12:55
# FIXED: 0004_add_memory_fields already adds the embedding column via raw SQL.
# This migration must only record the model state (no schema change),
# otherwise migrate fails on every fresh database with:
#   column "embedding" of relation "agent_memory" already exists

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_add_scheduled_one_time_task"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="agentmemory",
                    name="embedding",
                    field=pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]
