# Generated by Django 5.0.6 on 2026-04-07 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backtest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="信号名称")),
                ("symbol", models.CharField(max_length=32, verbose_name="交易对")),
                (
                    "interval",
                    models.CharField(
                        default="1h", max_length=8, verbose_name="K��周期"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="binance", max_length=32, verbose_name="数据源"
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(max_length=32, verbose_name="指标类型"),
                ),
                (
                    "indicator_params",
                    models.JSONField(default=dict, verbose_name="指标参数"),
                ),
                ("condition", models.JSONField(verbose_name="触发条件")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("once", "单次触发"), ("continuous", "持续触发")],
                        default="once",
                        max_length=16,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("notify", "发送通知"),
                            ("trade", "执行交易"),
                            ("notify_and_trade", "通知并交易"),
                        ],
                        default="notify",
                        max_length=20,
                        verbose_name="动作类型",
                    ),
                ),
                (
                    "action_params",
                    models.JSONField(default=dict, verbose_name="动作参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("triggered", "已触发"),
                            ("disabled", "已禁用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后触发时间"
                    ),
                ),
                (
                    "trigger_count",
                    models.IntegerField(default=0, verbose_name="触发次数"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backtest_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signal_monitors",
                        to="backtest.backtestresult",
                        verbose_name="关联回测",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_monitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "信号监控",
                "verbose_name_plural": "信号监控",
                "db_table": "signal_monitors",
            },
        ),
        migrations.CreateModel(
            name="SignalTriggerLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger_value", models.JSONField(verbose_name="触发时的指标值")),
                (
                    "action_result",
                    models.JSONField(default=dict, verbose_name="执行结果"),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_logs",
                        to="signal_monitor.signalmonitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "信号触发日志",
                "verbose_name_plural": "信号触发日志",
                "db_table": "signal_trigger_logs",
            },
        ),
        migrations.AddIndex(
            model_name="signalmonitor",
            index=models.Index(
                fields=["user", "status"], name="signal_moni_user_id_97d34c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalmonitor",
            index=models.Index(
                fields=["symbol", "interval", "status"],
                name="signal_moni_symbol_163baa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signalmonitor",
            index=models.Index(
                fields=["-created_at"], name="signal_moni_created_a50c1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signaltriggerlog",
            index=models.Index(
                fields=["monitor", "-executed_at"],
                name="signal_trig_monitor_f1a7bf_idx",
            ),
        ),
    ]
