# Generated by Django 5.0.6 on 2026-05-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signal_monitor', '0002_add_strategy_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='signalmonitor',
            name='signal_moni_strateg_c4e166_idx',
        ),
    ]
