# Generated by Django 5.0.6 on 2026-09-23 14:01
"""`ReduceStatus` 加了 ``no_op`` 一档，`status` 的 ``choices`` 跟着变。

## 这条迁移是纯元数据，不动数据也不动列型

``choices`` 只活在 Python 侧（Django 不把它写进 DDL），所以这次 ``AlterField`` 落到底
是**同一个 ``varchar(16)``** ——库里的值一个都不用改。已经写进去的四档（``claimed`` /
``succeeded`` / ``partial`` / ``failed``）原文不动，新档只对**之后**写下的行生效。

**没有反向数据迁移**，也不该有：把 ``no_op`` 的行在回滚时改成别的值，等于替写方断言
「那一次到底减没减」，而它恰恰是「无可减」那句话本身（见 ``ReduceStatus`` docstring
的三分类）。

## 为什么要跑这一条

不跑的话 ``makemigrations --check`` 一直红，而真正的代价不是那条红：``ReduceStatus``
是**通知与日报引用的一份词表**，库里存的是短码、显示时过 ``_REDUCE_STATUS_DISPLAY``。
少了 ``no_op``，写方一试就会在 ``ReduceStatus(record.status)`` 上抛 ``ValueError``——
而那时记录已经落库了，抛在**收尾**而不是**认领**，表现是「减仓做完了，通知发不出去」。
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regime', '0010_regimereducepause_regimereducerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimereducerecord',
            name='status',
            field=models.CharField(choices=[('claimed', '已认领（进行中）'), ('succeeded', '已减仓'), ('partial', '部分减仓'), ('failed', '减仓失败（确定未成交）'), ('no_op', '无需减仓（无可减）'), ('unsettled', '未得出结论（可能仍有活单）')], db_index=True, default='claimed', max_length=16, verbose_name='收场'),
        ),
    ]
