# Generated by Django 5.0.6 on 2026-09-24 02:00
"""`HaltDeclaration` 加两个「窗口通知发出去了没有」的时刻（第②段单元 ②e）。

## 为什么账记在这张表上、而不是另开一张订阅表

「这条窗口该通知谁」是**求值**出来的（受影响策略的活跃实盘会话），不是谁订的——事件熔断
不可人工豁免，通知是机制的责任而不是订阅的产物（`HaltDeclaration` docstring）。而订阅
表会与声明行各自漂移：声明行可以被窗口推进**原地改写**、可以被解除，订阅关系不会跟着动。
所以账记在行上，与 `DailyReport.delivery` 同一个先例。

## 为什么记时刻而不是布尔

只记「发过」的话，用户说没收到时答不出话；且第②e 段的规则是「**送达了才记账**」，记账
动作与那个时刻本来就是同一件事。

两列都 `null=True`，所以这次是两条纯 `AddField`——**不动已有数据**：②e 之前写下的行
两列都是空，于是首轮会把还开着的窗口各补一条「已开启」（真事，只补一次），而已经解除的
历史行不会补「已结束」（`pending_closed` 要求 `opened_notified_at` 非空）。
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regime', '0011_alter_regimereducerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='haltdeclaration',
            name='closed_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束通知时刻（UTC，空=未发）'),
        ),
        migrations.AddField(
            model_name='haltdeclaration',
            name='opened_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开窗通知时刻（UTC，空=未发）'),
        ),
    ]
