# Generated by Django 6.0.3 on 2026-03-28 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_loss_warning_pct", models.FloatField(default=0.03)),
                ("consecutive_loss_alert", models.IntegerField(default=3)),
                ("position_suggestion_limit", models.FloatField(default=0.1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "risk_configs",
            },
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("P0", "P0"), ("P1", "P1"), ("P2", "P2")], max_length=2
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hard_limit", "Hard Limit"),
                            ("circuit_breaker", "Circuit Breaker"),
                            ("reconciliation", "Reconciliation"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "risk_events",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="risk_events_created_766ed6_idx"
                    )
                ],
            },
        ),
    ]
