# Generated by Django 5.0.6 on 2026-04-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskconfig",
            name="auto_stop",
            field=models.BooleanField(default=True, help_text="触发风控条件时自动平仓"),
        ),
        migrations.AddField(
            model_name="riskconfig",
            name="max_drawdown_pct",
            field=models.FloatField(default=8.0, help_text="最大回撤限额 %"),
        ),
        migrations.AddField(
            model_name="riskconfig",
            name="max_position_pct",
            field=models.FloatField(default=35.0, help_text="最大仓位集中度 %"),
        ),
        migrations.AddField(
            model_name="riskconfig",
            name="stop_loss_pct",
            field=models.FloatField(default=2.0, help_text="止损阈值 %"),
        ),
        migrations.AddField(
            model_name="riskconfig",
            name="var_limit_pct",
            field=models.FloatField(default=3.0, help_text="日 VaR 限额 %"),
        ),
    ]
