# Generated by Django 6.0.3 on 2026-03-28 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code_path", models.CharField(max_length=256)),
                ("git_commit_hash", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "strategies",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("symbol", models.CharField(max_length=32)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("limit", "Limit"),
                            ("stop", "Stop"),
                        ],
                        max_length=8,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("partial", "Partial"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("exchange_order_id", models.CharField(blank=True, max_length=128)),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "avg_fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exchange.exchangeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="orders_created_b25042_idx"
                    ),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                ],
            },
        ),
    ]
