# Generated by Django 5.0.6 on 2026-04-14 03:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtest", "0005_add_live_session_and_order_link"),
        ("exchange", "0002_exchangeaccount_testnet"),
        ("trading", "0002_order_realized_pnl_order_user_dailysnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                (
                    "mode",
                    models.CharField(
                        choices=[("live", "实盘"), ("paper", "模拟")],
                        default="paper",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待启动"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("error", "异常"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "current_equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="运行参数（仓位比例、止损等）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backtest_result",
                    models.ForeignKey(
                        blank=True,
                        help_text="来源回测",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_sessions",
                        to="backtest.backtestresult",
                    ),
                ),
                (
                    "exchange_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="绑定的交易所账户",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exchange.exchangeaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "live_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="live_session",
            field=models.ForeignKey(
                blank=True,
                help_text="订单所属的实盘会话",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="trading.livesession",
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["user", "status"], name="live_sessio_user_id_933000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["user", "mode"], name="live_sessio_user_id_094834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livesession",
            index=models.Index(
                fields=["backtest_result"], name="live_sessio_backtes_4864cf_idx"
            ),
        ),
    ]
