# Generated by Django 5.0.6 on 2026-04-14 03:43

from django.db import migrations, models


def backfill_triggered_strategy(apps, schema_editor):
    """把历史订单从 live_session→strategy 联表结果写入快照字段。"""
    Order = apps.get_model("trading", "Order")
    for order in Order.objects.select_related("live_session__strategy").iterator():
        if (
            not order.triggered_strategy
            and order.live_session_id
            and getattr(order.live_session, "strategy_id", None)
        ):
            order.triggered_strategy = order.live_session.strategy.name
            order.save(update_fields=["triggered_strategy"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_add_live_session_and_order_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="triggered_strategy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="触发该订单的策略/信号名称（下单时快照，会话删除后仍保留）",
                max_length=128,
            ),
        ),
        migrations.RunPython(backfill_triggered_strategy, noop),
    ]
