# Generated by Django 5.0.6 on 2026-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceconfig',
            name='market_types',
            field=models.JSONField(blank=True, default=list, help_text='["spot"], ["futures"], 或同时配置。空列表=全部。'),
        ),
    ]
