# Generated by Django 5.0.6 on 2026-05-22 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=256, unique=True, verbose_name='CSRF State Token')),
                ('flow_type', models.CharField(choices=[('qr', 'QR Code'), ('url', 'URL Redirect')], default='qr', max_length=4)),
                ('status', models.CharField(choices=[('pending', '待扫码'), ('completed', '已完成'), ('expired', '已过期'), ('failed', '授权失败')], default='pending', max_length=16)),
                ('qr_url', models.TextField(blank=True, verbose_name='飞书授权链接')),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='二维码过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feishu 授权会话',
                'db_table': 'feishu_auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='FeishuUserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=128, unique=True, verbose_name='Feishu Open ID')),
                ('access_token_enc', models.BinaryField()),
                ('refresh_token_enc', models.BinaryField()),
                ('expires_at', models.DateTimeField(verbose_name='Access Token 过期时间')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feishu 用户 Token',
                'db_table': 'feishu_user_tokens',
            },
        ),
    ]
