# Generated by Django 5.0.6 on 2026-09-23 13:22

import logging

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)


def backfill_account_user(apps, schema_editor):
    """把「这个账户是谁的」从「会话 → 用户」反查出来，填进新增的 `user` 列。

    ## 判据：**恰好一个**用户用过这个账户

    只有这一种情形能填。多个用户用过同一个账户时，填谁都是错的——而填错的后果不是
    「通知发给了不相干的人」这么轻：减仓告警会发给一个不知道这笔仓位的人，真正该去
    处理的人收不到。所以宁可留空，让通知走「未归属 → 全体 is_active」那条明确的路径
    （`apps/regime/reduce_run.py` 的收件人解析，首行会写明「该账户未归属到具体用户」）。

    零个用户用过（纯新建、或只被人工在 admin 之外的地方配过）同样留空——「没有主人」
    与「不知道主人」在这张表里都是空值，而读取方对空值的处置是同一条。

    ## 数据源只用 `LiveSession`，不看 `Order`

    `Order.user` 是**下单请求人**，它可以是代下、可以是跑在别人会话里的策略，而
    `LiveSession` 的 `(user, exchange_account)` 是一次显式的绑定：用户开了一个实盘
    会话，会话指明了他用哪个账户。用订单表去投票会把一次误挂的单算作「另一个主人」，
    把本来干净的一账户推成歧义。这一列填错的代价（见上）远大于留空的代价，所以取更
    窄的那个数据源。

    ## 「记了数」记在哪

    留空的行本身就是记录——**空值就是这条判据的结论**，读取方必须显式处置它（这也是
    这一列写成可空的原因，见 `ExchangeAccount.user` 的注释）。除此之外这里只往迁移
    日志里写一行汇总，供执行迁移的人当场看见有几个账户落在了「未归属」上；它不是
    告警（迁移是一次性的、有人在旁边跑），也不伪装成告警。
    """
    ExchangeAccount = apps.get_model("exchange", "ExchangeAccount")
    LiveSession = apps.get_model("trading", "LiveSession")

    filled = ambiguous = unowned = 0
    accounts = ExchangeAccount.objects.filter(user__isnull=True).order_by("created_at", "id")
    for account in accounts:
        user_ids = list(
            LiveSession.objects.filter(exchange_account=account)
            .exclude(user__isnull=True)
            .values_list("user_id", flat=True)
            .distinct()
        )
        if len(user_ids) == 1:
            account.user_id = user_ids[0]
            account.save(update_fields=["user"])
            filled += 1
            continue
        if len(user_ids) > 1:
            ambiguous += 1
            logger.warning(
                "[exchange] 账户 %s (%s) 被 %s 个用户用过，归属留空",
                account.id,
                account.label,
                len(user_ids),
            )
        else:
            unowned += 1

    logger.info(
        "[exchange] 账户归属回填：绑定 %s，歧义留空 %s，无会话留空 %s（留空的行按"
        "「未归属」处置，通知发给全体 is_active 用户）",
        filled,
        ambiguous,
        unowned,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_deactivate_non_binance'),
        # 回填要读 `LiveSession`，所以必须等它建出来。
        ('trading', '0006_backfill_strategy_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='user',
            field=models.ForeignKey(blank=True, help_text='账户归属人（空 = 未归属，通知按全体 is_active 发）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL),
        ),
        # 反向是 noop：`user` 这一列本身会随 AddField 一起被删掉，而「回填」这件事
        # 在反向运行里没有可还原的原状（没有前值）。写一个「反向清空」更糟——它会连带
        # 抹掉回填之后由人手工指定的归属。
        migrations.RunPython(backfill_account_user, migrations.RunPython.noop),
    ]
