# Generated by Django 6.0.3 on 2026-03-28 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("timeframe", models.CharField(max_length=8)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("final_capital", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_return_pct", models.FloatField()),
                ("sharpe_ratio", models.FloatField(null=True)),
                ("max_drawdown_pct", models.FloatField(null=True)),
                ("win_rate", models.FloatField(null=True)),
                ("total_trades", models.IntegerField(default=0)),
                ("git_commit_hash", models.CharField(blank=True, max_length=40)),
                ("parameters", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "db_table": "backtest_results",
            },
        ),
    ]
