# Generated by Django 5.0.6 on 2026-04-13 12:50

from django.db import migrations, models


def _uuid_pk_to_bigint(apps, schema_editor):
    """Convert backtest_trades.id from UUID to bigint identity.

    Plain AlterField cannot do this on PostgreSQL (no uuid->bigint cast).
    Safe for both empty tables and tables with existing rows (old uuid
    values are dropped; rows get fresh sequential ids).
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    table = "backtest_trades"
    with schema_editor.connection.cursor() as cur:
        cur.execute(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = %s::regclass AND contype = %s",
            [table, "p"],
        )
        row = cur.fetchone()
        if row:
            cur.execute("ALTER TABLE backtest_trades DROP CONSTRAINT " + row[0])
        cur.execute("ALTER TABLE backtest_trades RENAME COLUMN id TO id_old")
        cur.execute(
            "ALTER TABLE backtest_trades ADD COLUMN id bigint "
            "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        )
        cur.execute("ALTER TABLE backtest_trades DROP COLUMN id_old")


def _no_reverse(apps, schema_editor):
    # Irreversible: original uuid values are not preserved.
    pass



class Migration(migrations.Migration):
    dependencies = [
        ("backtest", "0003_add_ohlcv_and_indicators"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="backtesttrade",
            name="backtest_tr_backtes_29c5f0_idx",
        ),
        migrations.RemoveIndex(
            model_name="backtesttrade",
            name="backtest_tr_backtes_27cd7e_idx",
        ),
        migrations.RemoveField(
            model_name="backtesttrade",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="backtesttrade",
            name="cumulative_pnl",
        ),
        migrations.RemoveField(
            model_name="backtesttrade",
            name="fees",
        ),
        migrations.RemoveField(
            model_name="backtesttrade",
            name="symbol",
        ),
        migrations.RemoveField(
            model_name="backtesttrade",
            name="tags",
        ),
        migrations.AddField(
            model_name="backtesttrade",
            name="commission",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=0, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="backtesttrade",
            name="exit_reason",
            field=models.CharField(
                blank=True,
                help_text="Why this trade was closed (stop_loss, take_profit, signal, etc.)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="backtesttrade",
            name="signal",
            field=models.CharField(
                blank=True, help_text="What signal triggered this trade", max_length=64
            ),
        ),
        migrations.RunPython(_uuid_pk_to_bigint, _no_reverse),
        migrations.AlterField(
            model_name="backtesttrade",
            name="pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="backtesttrade",
            name="side",
            field=models.CharField(
                choices=[("long", "Long"), ("short", "Short")], max_length=5
            ),
        ),
    ]
