# Generated by Django 5.0.6 on 2026-05-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0008_grid_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GridSearchSchedule',
        ),
    ]
